export const CONTINENTS = [
  { key: "all", i18nKey: "continent.all" },
  {
    key: "europe",
    i18nKey: "continent.europe",
    countries: [
      "England",
      "Spain",
      "Italy",
      "Germany",
      "France",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Turkey",
      "Scotland",
      "Russia",
      "Ukraine",
      "Greece",
      "Austria",
      "Switzerland",
      "Poland",
      "Czech Republic",
      "Denmark",
      "Sweden",
      "Norway",
    ],
  },
  {
    key: "asia",
    i18nKey: "continent.asia",
    countries: [
      "Uzbekistan",
      "South Korea",
      "Japan",
      "China",
      "Saudi Arabia",
      "UAE",
      "Qatar",
      "Iran",
      "Thailand",
      "Malaysia",
      "Indonesia",
      "Vietnam",
      "India",
      "Australia",
    ],
  },
  {
    key: "south-america",
    i18nKey: "continent.southAmerica",
    countries: [
      "Brazil",
      "Argentina",
      "Uruguay",
      "Chile",
      "Colombia",
      "Peru",
      "Paraguay",
      "Ecuador",
      "Bolivia",
      "Venezuela",
    ],
  },
  {
    key: "north-america",
    i18nKey: "continent.northAmerica",
    countries: ["USA", "Mexico", "Canada", "Costa Rica"],
  },
  {
    key: "africa",
    i18nKey: "continent.africa",
    countries: [
      "Egypt",
      "Morocco",
      "Tunisia",
      "Algeria",
      "South Africa",
      "Nigeria",
      "Ghana",
      "Senegal",
      "Cameroon",
      "Ivory Coast",
    ],
  },
];

export const SEASON = 2025;
export const MATCH_SEASON = 2025;
export const STANDING_SEASON = 2025;

export const FEATURED_LEAGUES = [
  { id: 39, name: "Premier League", totalRounds: 38, color: "#3D195B" },
  { id: 140, name: "La Liga", totalRounds: 38, color: "#FF4B44" },
  { id: 61, name: "Ligue 1", totalRounds: 34, color: "#1B3D6E" },
  { id: 78, name: "Bundesliga", totalRounds: 34, color: "#D3010C" },
  { id: 135, name: "Serie A", totalRounds: 38, color: "#1A56A6" },
  {
    id: 369,
    name: "Uzbekistan Super League",
    totalRounds: 26,
    color: "#1E8449",
  },
  { id: 802, name: "Uzbekistan Cup", totalRounds: null, color: "#1E8449" },
  { id: 2, name: "UEFA Champions League", totalRounds: 8, color: "#1B3A6B" },
  { id: 3, name: "UEFA Europa League", totalRounds: 8, color: "#F47A30" },
  { id: 848, name: "UEFA Conference League", totalRounds: 8, color: "#00A550" },
  { id: 203, name: "Süper Lig", totalRounds: 38, color: "#E30A17" },
  { id: 94, name: "Primeira Liga", totalRounds: 34, color: "#006600" },
  { id: 88, name: "Eredivisie", totalRounds: 34, color: "#FF6600" },
  { id: 307, name: "Saudi Pro League", totalRounds: 30, color: "#006C35" },
  { id: 253, name: "MLS", totalRounds: 34, color: "#002F6C" },
  { id: 17, name: "AFC Champions League", totalRounds: null, color: "#C8102E" },
  { id: 32, name: "AFC Asian Qualifiers", totalRounds: null, color: "#C8102E" },
  { id: 1, name: "World Cup", totalRounds: null, color: "#8B0000" },
  { id: 4, name: "Euro Championship", totalRounds: null, color: "#003399" },
  { id: 9, name: "Copa America", totalRounds: null, color: "#0A3161" },
  { id: 31, name: "AFC Asian Cup", totalRounds: null, color: "#C8102E" },
  { id: 5, name: "UEFA Nations League", totalRounds: null, color: "#003399" },
];
