export const CONTINENTS = [
  { key: "all", label: "전체" },
  {
    key: "europe",
    label: "유럽",
    countries: [
      "England",
      "Spain",
      "Italy",
      "Germany",
      "France",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Turkey",
      "Scotland",
      "Russia",
      "Ukraine",
      "Greece",
      "Austria",
      "Switzerland",
      "Poland",
      "Czech Republic",
      "Denmark",
      "Sweden",
      "Norway",
    ],
  },
  {
    key: "asia",
    label: "아시아",
    countries: [
      "Uzbekistan",
      "South Korea",
      "Japan",
      "China",
      "Saudi Arabia",
      "UAE",
      "Qatar",
      "Iran",
      "Thailand",
      "Malaysia",
      "Indonesia",
      "Vietnam",
      "India",
      "Australia",
    ],
  },
  {
    key: "south-america",
    label: "남미",
    countries: [
      "Brazil",
      "Argentina",
      "Uruguay",
      "Chile",
      "Colombia",
      "Peru",
      "Paraguay",
      "Ecuador",
      "Bolivia",
      "Venezuela",
    ],
  },
  {
    key: "north-america",
    label: "북미",
    countries: ["USA", "Mexico", "Canada", "Costa Rica"],
  },
  {
    key: "africa",
    label: "아프리카",
    countries: [
      "Egypt",
      "Morocco",
      "Tunisia",
      "Algeria",
      "South Africa",
      "Nigeria",
      "Ghana",
      "Senegal",
      "Cameroon",
      "Ivory Coast",
    ],
  },
];
