export const CONTINENTS = [
  { key: "all", i18nKey: "continent.all" },
  {
    key: "europe",
    i18nKey: "continent.europe",
    countries: [
      "England",
      "Spain",
      "Italy",
      "Germany",
      "France",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Turkey",
      "Scotland",
      "Russia",
      "Ukraine",
      "Greece",
      "Austria",
      "Switzerland",
      "Poland",
      "Czech Republic",
      "Denmark",
      "Sweden",
      "Norway",
    ],
  },
  {
    key: "asia",
    i18nKey: "continent.asia",
    countries: [
      "Uzbekistan",
      "South Korea",
      "Japan",
      "China",
      "Saudi Arabia",
      "UAE",
      "Qatar",
      "Iran",
      "Thailand",
      "Malaysia",
      "Indonesia",
      "Vietnam",
      "India",
      "Australia",
    ],
  },
  {
    key: "south-america",
    i18nKey: "continent.southAmerica",
    countries: [
      "Brazil",
      "Argentina",
      "Uruguay",
      "Chile",
      "Colombia",
      "Peru",
      "Paraguay",
      "Ecuador",
      "Bolivia",
      "Venezuela",
    ],
  },
  {
    key: "north-america",
    i18nKey: "continent.northAmerica",
    countries: ["USA", "Mexico", "Canada", "Costa Rica"],
  },
  {
    key: "africa",
    i18nKey: "continent.africa",
    countries: [
      "Egypt",
      "Morocco",
      "Tunisia",
      "Algeria",
      "South Africa",
      "Nigeria",
      "Ghana",
      "Senegal",
      "Cameroon",
      "Ivory Coast",
    ],
  },
];

export const SEASON = 2024;
export const MATCH_SEASON = 2025;
export const STANDING_SEASON = 2024;
